name: "ECS PROD Audit"

on:
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Run ECS audit script.
        run: |
          aws ecs list-services --cluster github-ephemeral-test --output text | awk '{print $2}' | while read -r service; do
              task_definition=$(aws ecs describe-services --cluster github-ephemeral-test --services $service --query 'services[0].taskDefinition' --output text)
              image=$(aws ecs describe-task-definition --task-definition $task_definition --query 'taskDefinition.containerDefinitions[0].image' --output text)
              echo "Service: $service, Image: $image"
          done
